backend:
      name: git-gateway
      commit_messages:
        create: 'Create {{collection}} “{{slug}}”'
        update: 'Update {{collection}} “{{slug}}”'
        delete: 'Delete {{collection}} “{{slug}}”'
        uploadMedia: '[skip ci] Upload “{{path}}”'
        deleteMedia: '[skip ci] Delete “{{path}}”'
media_folder: src/images/uploads
public_folder: src/images/uploads
logo_url: 'https://www.yarcenter.org/icons/icon-512x512.png'
publish_mode: editorial_workflow
site_url: https://yarcenter.org

local_backend: true

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: "{{slug}}-{{month}}-{{year}}"
    editor:
      preview: true
    preview_path: blog/{{slug}}
    preview_path_date_field: date
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Author', name: 'author', widget: 'string' }
      - label: 'Image'
        name: blogImg
        widget: 'image'
        required: false
        hint: >
          This is optional. This image will not be displayed in the blog post, but on the preview card that links to this post.
          You can optionally insert an image, link, or video link in the blog post.
      - { label: 'Tags', name: 'tags', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'blog'}
  - name: 'event'
    label: "Events"
    folder: src/pages/events
    slug: "{{slug}}-{{year}}"
    create: true
    preview_path: events/{{slug}}
    preview_path_date_field: startDate
    fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date:', name: 'startDate', widget: 'date' }
      - label: 'Image'
        name: 'eventImage'
        widget: 'image'
        required: false
        hint: "This is optional. Image can be added from within the text box below, or added here to be alongside the text content" 
      - { label: 'Description', name: 'description', widget: 'string', required: false}
      - { label: 'Tags', name: 'tags', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'event'}
  - name: 'programs'
    label: "Programs"
    folder: src/pages/programs
    slug: "{{slug}}-{{year}}"
    create: true
    preview_path: programs/{{slug}}
    preview_path_date_field: startDate
    fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Starts:', name: 'startDate', widget: 'date' }
      - { label: 'Ends::', name: 'endDate', widget: 'date' }
      - label: 'Image'
        name: 'programImage'
        widget: 'image'
        required: false
        hint: "This is optional. Image can be embedded in the text box as well"
      - { label: 'Description', name: 'description', widget: 'string', required: false}
      - { label: 'Tags', name: 'tags', widget: 'string'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'program'}
  - name: pages
    label: "Site Pages"
    create: false
    editor:
      preview: true
    files:
      - file: src/pages/index.md
        label: "Home Page"
        name: index
        fields:
          - { label: "BackgroundImage", name: bgImage, widget: image }    
          - { label: 'Main Text', name: head, widget: 'string'}
          - { label: "Sub Text", name: caption, widget: 'string' }
          - label: "Icon Cards" 
            name: section1
            widget: object
            fields:
              - label: "Left Card" 
                name: card1 
                widget: object 
                fields:
                  - {label: "Main Text", name: head, widget: string}
                  - {label: "Sub Text", name: body, widget: string}
              - label: "Center Card" 
                name: card2 
                widget: object 
                fields:
                  - {label: "Main Text", name: head, widget: string}
                  - {label: "Sub Text", name: body, widget: string}
              - label: "Right Card" 
                name: card3 
                widget: object 
                fields:
                  - {label: "Main Text", name: head, widget: string}
                  - {label: "Sub Text", name: body, widget: string}
          - label: "Events Section" 
            name: section2
            widget: object
            fields:
              - label: "Left Text" 
                name: side
                widget: object 
                fields:
                  - {label: "Main Text", name: head, widget: string}
                  - {label: "Sub Text", name: body, widget: string}
              - label: "Slant Card" 
                name: slantCard 
                widget: object 
                fields:
                  - {label: "Main Text", name: head, widget: string}
                  - {label: "Sub Text", name: body, widget: string}
                  - {label: "Image", name: image, widget: image}
              - label: "Link Text"
                name: linkText
                widget: string
          - label: Programs Section
            name: section3
            widget: object
            fields:
              - label: Side Text
                name: side
                widget: object
                fields:
                  - { label: "Main Text", name: head, widget: string}
                  - { label: "Sub Text", name: body, widget: string}
              - { label: Image, name: image, widget: image }
              - { label: Link Text, name: linkText, widget: string }
          - label: Team Section
            name: section4
            widget: object
            fields:
              - { label: Main , name: head, widget: string }
              - { label: Sub Text, name: body, widget: string }
              - label: Staff 1
                name: card1
                widget: object
                fields:
                  - { label: Name, name: member, widget: string }
                  - { label: "Title", name: title, widget: string }
                  - { label: Image, name: image, widget: image }
              - label: Staff 2
                name: card2
                widget: object
                fields:
                  - { label: Name, name: member, widget: string }
                  - { label: "Title", name: title, widget: string }
                  - { label: Image, name: image, widget: image }
              - label: Staff 3
                name: card3
                widget: object
                fields:
                  - { label: Name, name: member, widget: string }
                  - { label: "Title", name: title, widget: string }
                  - { label: Image, name: image, widget: image }
              - label: Staff 4
                name: card4
                widget: object
                fields:
                  - { label: Name, name: member, widget: string }
                  - { label: "Title", name: title, widget: string }
                  - { label: Image, name: image, widget: image }
            
